server:
  port: 8082

spring:
  name: capacidad-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/capacidades_db
    username: root
    password: root

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
